export default function Head (){
    return (
        <>
            <title>Create Next App</title>
            <meta content="width=device-width, initial-sacale=1" name="view"/>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="/favicon.ico" />
        </>
    )
}